# Shortcuts
alias copyssh="pbcopy < $HOME/.ssh/id_rsa.pub"
alias reloadcli="source $HOME/.zshrc"
alias ls="ls -GFhal"
alias gg="git status"
alias glog="git log --graph --abbrev-commit --decorate -all"
alias gb="git branch -a"
alias gba="git branch -a"
alias gc-="git checkout -"
alias gfap="git fetch --all --prune"
alias grp="git remote prune origin"
alias openzsh="code ~/.zshrc"
alias yrd="yarn run dev"
alias yrs="yarn run start"
alias npmbin="Path=$(npm bin):$PATH"

# Directories
alias dotfiles="cd $DOTFILES"
alias library="cd $HOME/Library"
alias sites="cd $HOME/Sites"
